// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vkpgvpzubmetctymflwu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZrcGd2cHp1Ym1ldGN0eW1mbHd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzNDA3MTAsImV4cCI6MjA1ODkxNjcxMH0.VMNdyL_6wrRSX9adtys7DUNzSnydbV7vH_U3uOk8_24";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);